In [2]:
import pandas as pd

In [3]:
# pip , conda, uv, mamba, ...

In [4]:
data = pd.read_csv("customer_shopping_data.csv")
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon
...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul

In [5]:
# Exploration

In [6]:
data.shape

(99457, 10)

In [7]:
data.columns

Index(['invoice_no', 'customer_id', 'gender', 'age', 'category', 'quantity',
       'price', 'payment_method', 'invoice_date', 'shopping_mall'],
      dtype='object')

In [8]:
data["gender"]

0        Female
1          Male
2          Male
3        Female
4        Female
          ...
99452    Female
99453      Male
99454      Male
99455      Male
99456    Female
Name: gender, Length: 99457, dtype: object

In [9]:
data[["gender"]]

       gender
0      Female
1        Male
2        Male
3      Female
4      Female
...       ...
99452  Female
99453    Male
99454    Male
99455    Male
99456  Female

[99457 rows x 1 columns]

In [10]:
data.gender

0        Female
1          Male
2          Male
3        Female
4        Female
          ...
99452    Female
99453      Male
99454      Male
99455      Male
99456    Female
Name: gender, Length: 99457, dtype: object

In [11]:
type(data)

pandas.core.frame.DataFrame

In [12]:
data.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon

In [13]:
data.tail()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul

In [14]:
data.head(3)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity

In [15]:
data.tail(3)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul

In [16]:
data[ 0 : 3 ]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity

In [17]:
data[ 0 : 1 ]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.4,Credit Card,5/8/2022,Kanyon

In [20]:
type(data.gender)

pandas.core.series.Series

In [21]:
data.gender

0        Female
1          Male
2          Male
3        Female
4        Female
          ...
99452    Female
99453      Male
99454      Male
99455      Male
99456    Female
Name: gender, Length: 99457, dtype: object

In [22]:
data.gender.values

array(['Female', 'Male', 'Male', ..., 'Male', 'Male', 'Female'],
      dtype=object)

In [23]:
type(data.gender.values)

numpy.ndarray

In [24]:
data.head(30)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon
5,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,24/05/2022,Forum Istanbul
6,I121056,C151197,Female,49,Cosmetics,1,40.66,Cash,13/03/2022,Istinye Park
7,I293112,C176086,Female,32,Clothing,2,600.16,Credit Card,13/01/2021,Mall of Istanbul
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,4/11/2021,Metrocity
9,I326945,C283361,Female,60,Clothing,2,600.16,Credit Card,22/08/2021,Kanyon
10,I306368,C240286,Female,36,Food & Beverage,2,10.46,Cash,25/12/2022,Metrocity
11,I139207,C191708,Female,29,Books,1,15.15,Credit Card,28/10/2022,Emaar Square Mall
12,I640508,C225330,Female,67,Toys,4,143.36,Debit Card,31/07/2022,Metrocity
13,I179802,C312861,Male,25,Clothing,2,600.16,Cash,17/11/2022,Cevahir AVM
14,I336189,C555402,Female,67,Clothing,2,600.16,Credit Card,3/6/2022,Kanyon
15,I688768,C362288,Male,24,Shoes,5,3000.85,Credit Card,7/11/2021,Viaport Outlet
16,I294687,C300786,Male,65,Books,2,30.30,Debit Card,16/01/2021,Metrocity
17,I195744,C330667,Female,42,Food & Beverage,3,15.69,Credit Card,5/1/2022,Zorlu Center
18,I993048,C218149,Female,46,Clothing,2,600.16,Cash,26/07/2021,Metropol AVM
19,I992454,C196845,Male,24,Toys,4,143.36,Cash,7/3/2023,Cevahir AVM
20,I183746,C220180,Male,23,Clothing,1,300.08,Credit Card,15/02/2023,Emaar Square Mall
21,I412481,C125696,Female,27,Food & Beverage,1,5.23,Cash,1/5/2021,Cevahir AVM
22,I823067,C322947,Male,52,Clothing,2,600.16,Credit Card,18/06/2022,Cevahir AVM
23,I252275,C313348,Male,44,Technology,5,5250.00,Cash,26/10/2021,Kanyon
24,I174250,C204553,Female,42,Books,5,75.75,Cash,16/12/2022,Metrocity
25,I195396,C285161,Male,51,Toys,2,71.68,Debit Card,16/05/2021,Istinye Park
26,I196704,C289625,Female,25,Cosmetics,5,203.30,Credit Card,20/04/2022,Mall of Istanbul
27,I217053,C192344,Male,50,Shoes,4,2400.68,Cash,10/10/2022,Emaar Square Mall
28,I655874,C447138,Female,65,Shoes,3,1800.51,Cash,23/08/2022,Cevahir AVM
29,I209744,C251229,Male,29,Cosmetics,3,121.98,Credit Card,29/04/2021,Istinye Park

In [25]:
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon
...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul

In [26]:
data.age

0        28
1        21
2        20
3        66
4        53
         ..
99452    45
99453    27
99454    63
99455    56
99456    36
Name: age, Length: 99457, dtype: int64

In [27]:
data.age.min()

18

In [28]:
data.age.max()

69

In [29]:
data.age.sum()

4319128

In [30]:
data.age.mean()

43.42708909377922

In [31]:
data.age.median()

43.0

In [32]:
data.age.mode()

0    37
Name: age, dtype: int64

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   gender          99457 non-null  object
 3   age             99457 non-null  int64
 4   category        99457 non-null  object
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object
 8   invoice_date    99457 non-null  object
 9   shopping_mall   99457 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 7.6+ MB

In [34]:
data.describe()

                age      quantity         price
count  99457.000000  99457.000000  99457.000000
mean      43.427089      3.003429    689.256321
std       14.990054      1.413025    941.184567
min       18.000000      1.000000      5.230000
25%       30.000000      2.000000     45.450000
50%       43.000000      3.000000    203.300000
75%       56.000000      4.000000   1200.320000
max       69.000000      5.000000   5250.000000

In [35]:
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon
...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul

In [36]:
data.quantity.max()

5

In [37]:
data.quantity.dtype

dtype('int64')

In [38]:
data.quantity = data.quantity.astype("int8")

In [39]:
data.quantity

0        5
1        3
2        1
3        5
4        4
        ..
99452    5
99453    2
99454    2
99455    4
99456    3
Name: quantity, Length: 99457, dtype: int8

In [40]:
data.quantity.dtype

dtype('int8')

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   gender          99457 non-null  object
 3   age             99457 non-null  int64
 4   category        99457 non-null  object
 5   quantity        99457 non-null  int8
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object
 8   invoice_date    99457 non-null  object
 9   shopping_mall   99457 non-null  object
dtypes: float64(1), int64(1), int8(1), object(7)
memory usage: 6.9+ MB

In [42]:
data.head(10)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon
5,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,24/05/2022,Forum Istanbul
6,I121056,C151197,Female,49,Cosmetics,1,40.66,Cash,13/03/2022,Istinye Park
7,I293112,C176086,Female,32,Clothing,2,600.16,Credit Card,13/01/2021,Mall of Istanbul
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,4/11/2021,Metrocity
9,I326945,C283361,Female,60,Clothing,2,600.16,Credit Card,22/08/2021,Kanyon

In [43]:
data[10: 11]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
10,I306368,C240286,Female,36,Food & Beverage,2,10.46,Cash,25/12/2022,Metrocity

In [44]:
data.loc[10]

invoice_no                I306368
customer_id               C240286
gender                     Female
age                            36
category          Food & Beverage
quantity                        2
price                       10.46
payment_method               Cash
invoice_date           25/12/2022
shopping_mall           Metrocity
Name: 10, dtype: object

In [45]:
data.loc[3]["category"]

'Shoes'

In [47]:
data.loc[3][4]

/var/folders/_r/3sb29fjj12d916yfxyrhd_gc0000gn/T/ipykernel_10548/2889319662.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data.loc[3][4]

'Shoes'

In [48]:
data.loc[3, 4]

KeyError: 4

In [49]:
data.iloc[3, 4]

'Shoes'

In [50]:
# select * from data where gender = Male; 

data [ data.gender == "Male"]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,4/11/2021,Metrocity
13,I179802,C312861,Male,25,Clothing,2,600.16,Cash,17/11/2022,Cevahir AVM
15,I688768,C362288,Male,24,Shoes,5,3000.85,Credit Card,7/11/2021,Viaport Outlet
...,...,...,...,...,...,...,...,...,...,...
99449,I134399,C953724,Male,65,Clothing,1,300.08,Cash,1/1/2023,Kanyon
99451,I675411,C513603,Male,50,Toys,5,179.20,Cash,9/10/2021,Metropol AVM
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park

In [51]:
data [ data.age == 20  ]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
191,I156233,C161285,Female,20,Clothing,1,300.08,Credit Card,11/1/2023,Mall of Istanbul
220,I798213,C662958,Female,20,Shoes,3,1800.51,Cash,3/1/2021,Metropol AVM
239,I204147,C252021,Female,20,Shoes,3,1800.51,Credit Card,5/11/2022,Kanyon
290,I281274,C130479,Male,20,Clothing,1,300.08,Cash,4/9/2022,Kanyon
...,...,...,...,...,...,...,...,...,...,...
99036,I173503,C107419,Male,20,Toys,2,71.68,Debit Card,20/04/2021,Zorlu Center
99045,I235989,C307974,Male,20,Clothing,3,900.24,Cash,23/12/2021,Cevahir AVM
99193,I326396,C293279,Female,20,Shoes,2,1200.34,Credit Card,27/01/2022,Kanyon
99299,I711950,C212383,Female,20,Food & Beverage,1,5.23,Debit Card,30/05/2022,Istinye Park
99309,I337751,C253676,Female,20,Clothing,4,1200.32,Cash,1/11/2021,Cevahir AVM

In [52]:
data [ data.category == "Clothing"]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
5,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,24/05/2022,Forum Istanbul
7,I293112,C176086,Female,32,Clothing,2,600.16,Credit Card,13/01/2021,Mall of Istanbul
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,4/11/2021,Metrocity
...,...,...,...,...,...,...,...,...,...,...
99435,I141871,C298790,Female,62,Clothing,3,900.24,Cash,2/2/2022,Emaar Square Mall
99436,I579905,C265057,Female,57,Clothing,5,1500.40,Cash,27/03/2022,Cevahir AVM
99440,I887161,C137631,Female,58,Clothing,1,300.08,Cash,22/06/2021,Kanyon
99442,I105959,C131810,Female,45,Clothing,4,1200.32,Debit Card,1/2/2021,Istinye Park
99449,I134399,C953724,Male,65,Clothing,1,300.08,Cash,1/1/2023,Kanyon

In [53]:
data.age.max()

69

In [54]:
data [ data.age == data.age.max() ]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,4/11/2021,Metrocity
77,I115870,C135790,Female,69,Shoes,4,2400.68,Cash,4/9/2021,Metrocity
211,I226172,C171154,Female,69,Shoes,1,600.17,Cash,24/07/2021,Kanyon
212,I737630,C848969,Male,69,Clothing,5,1500.40,Cash,15/04/2022,Metropol AVM
282,I263818,C336232,Male,69,Souvenir,4,46.92,Cash,26/06/2022,Zorlu Center
...,...,...,...,...,...,...,...,...,...,...
98796,I146016,C203641,Female,69,Technology,2,2100.00,Cash,2/2/2023,Viaport Outlet
98839,I214432,C685875,Male,69,Toys,4,143.36,Cash,22/07/2022,Metropol AVM
99007,I173132,C955663,Female,69,Clothing,3,900.24,Credit Card,10/10/2022,Mall of Istanbul
99043,I482625,C274732,Female,69,Cosmetics,1,40.66,Cash,13/12/2022,Metrocity
99321,I234667,C321665,Male,69,Food & Beverage,1,5.23,Debit Card,11/10/2021,Metropol AVM

In [56]:
data [ data.age.between(30,40) ]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
7,I293112,C176086,Female,32,Clothing,2,600.16,Credit Card,13/01/2021,Mall of Istanbul
10,I306368,C240286,Female,36,Food & Beverage,2,10.46,Cash,25/12/2022,Metrocity
32,I768348,C176727,Female,32,Shoes,3,1800.51,Credit Card,23/02/2022,Kanyon
43,I826174,C607615,Female,40,Shoes,4,2400.68,Cash,20/06/2022,Metrocity
59,I335713,C158837,Female,36,Books,4,60.60,Cash,14/12/2021,Kanyon
...,...,...,...,...,...,...,...,...,...,...
99441,I203187,C235554,Male,38,Food & Beverage,4,20.92,Cash,2/3/2023,Zorlu Center
99445,I750456,C270290,Female,35,Food & Beverage,5,26.15,Cash,7/5/2021,Kanyon
99446,I327966,C107209,Female,32,Food & Beverage,1,5.23,Cash,5/2/2023,Metropol AVM
99447,I281214,C288090,Female,37,Toys,3,107.52,Cash,21/02/2021,Metropol AVM
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul

In [57]:
data["category"][:5]

0    Clothing
1       Shoes
2    Clothing
3       Shoes
4       Books
Name: category, dtype: object

In [59]:
data[data.age == 20]["customer_id"]

2        C266599
191      C161285
220      C662958
239      C252021
290      C130479
          ...
99036    C107419
99045    C307974
99193    C293279
99299    C212383
99309    C253676
Name: customer_id, Length: 1844, dtype: object

In [60]:
data [["gender", "age"]]

       gender  age
0      Female   28
1        Male   21
2        Male   20
3      Female   66
4      Female   53
...       ...  ...
99452  Female   45
99453    Male   27
99454    Male   63
99455    Male   56
99456  Female   36

[99457 rows x 2 columns]

In [61]:
data[ data.price > 1500]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
5,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,24/05/2022,Forum Istanbul
15,I688768,C362288,Male,24,Shoes,5,3000.85,Credit Card,7/11/2021,Viaport Outlet
...,...,...,...,...,...,...,...,...,...,...
99424,I549710,C541824,Female,34,Technology,3,3150.00,Cash,13/01/2021,Metrocity
99430,I336082,C316368,Male,26,Clothing,5,1500.40,Cash,26/04/2021,Mall of Istanbul
99436,I579905,C265057,Female,57,Clothing,5,1500.40,Cash,27/03/2022,Cevahir AVM
99448,I332105,C231387,Female,65,Shoes,4,2400.68,Credit Card,29/08/2021,Metropol AVM
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park

In [64]:
data[ data.price > 1500].shape[(0)]

16996

In [65]:
data.gender

0        Female
1          Male
2          Male
3        Female
4        Female
          ...
99452    Female
99453      Male
99454      Male
99455      Male
99456    Female
Name: gender, Length: 99457, dtype: object

In [66]:
data.shopping_mall

0                  Kanyon
1          Forum Istanbul
2               Metrocity
3            Metropol AVM
4                  Kanyon
               ...
99452              Kanyon
99453      Forum Istanbul
99454           Metrocity
99455        Istinye Park
99456    Mall of Istanbul
Name: shopping_mall, Length: 99457, dtype: object

In [67]:
data.shopping_mall.max()

'Zorlu Center'

In [68]:
data.shopping_mall.value_counts()

shopping_mall
Mall of Istanbul     19943
Kanyon               19823
Metrocity            15011
Metropol AVM         10161
Istinye Park          9781
Zorlu Center          5075
Cevahir AVM           4991
Forum Istanbul        4947
Viaport Outlet        4914
Emaar Square Mall     4811
Name: count, dtype: int64

In [69]:
data.shopping_mall.value_counts()[0]

/var/folders/_r/3sb29fjj12d916yfxyrhd_gc0000gn/T/ipykernel_10548/3347848034.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data.shopping_mall.value_counts()[0]

19943

In [71]:
data.shopping_mall.value_counts().idxmax()

'Mall of Istanbul'

In [72]:
data.shopping_mall.value_counts().max()

19943

In [73]:
data.isna().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [74]:
data.customer_id.value_counts()

customer_id
C241288    1
C116138    1
C382765    1
C285074    1
C405356    1
          ..
C220083    1
C286933    1
C301304    1
C214184    1
C273973    1
Name: count, Length: 99457, dtype: int64

In [75]:
data.customer_id.duplicated().sum()

0

In [77]:
data.customer_id.duplicated().sum()

0

In [78]:
data.quantity.value_counts()

quantity
3    20149
5    19990
2    19828
1    19767
4    19723
Name: count, dtype: int64

In [79]:
data.payment_method.value_counts()

payment_method
Cash           44447
Credit Card    34931
Debit Card     20079
Name: count, dtype: int64

In [81]:
data["invoice_date"].dtype

dtype('O')

In [83]:
data["date"] = pd.to_datetime(data.invoice_date)

ValueError: time data "16/05/2021" doesn't match format "%m/%d/%Y", at position 3. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [82]:
data["total_amount"] = data.quantity * data.price 
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40
...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57

In [84]:
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40
...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57

In [85]:
data["date"] = pd.to_datetime(data.invoice_date, dayfirst = True)
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24
...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15

In [86]:
data.date.dtype

dtype('<M8[ns]')

In [87]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   gender          99457 non-null  object
 3   age             99457 non-null  int64
 4   category        99457 non-null  object
 5   quantity        99457 non-null  int8
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object
 8   invoice_date    99457 non-null  object
 9   shopping_mall   99457 non-null  object
 10  total_amount    99457 non-null  float64
 11  date            99457 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), int8(1), object(7)
memory usage: 8.4+ MB

In [88]:
data["day"] = data.date.dt.day
data["month"] = data.date.dt.month
data["year"] = data.date.dt.year
data["month/year"] = data.date.dt.to_period("M")
data["quarter"] = data.date.dt.quarter
data["week"] = data.date.dt.isocalendar().week

In [89]:
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [90]:
data[ data.year == 2022]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
5,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,24/05/2022,Forum Istanbul,7502.00,2022-05-24,24,5,2022,2022-05,2,21
6,I121056,C151197,Female,49,Cosmetics,1,40.66,Cash,13/03/2022,Istinye Park,40.66,2022-03-13,13,3,2022,2022-03,1,10
10,I306368,C240286,Female,36,Food & Beverage,2,10.46,Cash,25/12/2022,Metrocity,20.92,2022-12-25,25,12,2022,2022-12,4,51
11,I139207,C191708,Female,29,Books,1,15.15,Credit Card,28/10/2022,Emaar Square Mall,15.15,2022-10-28,28,10,2022,2022-10,4,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99434,I186560,C117024,Female,39,Shoes,1,600.17,Cash,21/03/2022,Kanyon,600.17,2022-03-21,21,3,2022,2022-03,1,12
99435,I141871,C298790,Female,62,Clothing,3,900.24,Cash,2/2/2022,Emaar Square Mall,2700.72,2022-02-02,2,2,2022,2022-02,1,5
99436,I579905,C265057,Female,57,Clothing,5,1500.40,Cash,27/03/2022,Cevahir AVM,7502.00,2022-03-27,27,3,2022,2022-03,1,12
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [91]:
data[ data.month == 11]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,4/11/2021,Metrocity,2700.72,2021-11-04,4,11,2021,2021-11,4,44
13,I179802,C312861,Male,25,Clothing,2,600.16,Cash,17/11/2022,Cevahir AVM,1200.32,2022-11-17,17,11,2022,2022-11,4,46
15,I688768,C362288,Male,24,Shoes,5,3000.85,Credit Card,7/11/2021,Viaport Outlet,15004.25,2021-11-07,7,11,2021,2021-11,4,44
31,I331891,C501658,Male,23,Clothing,1,300.08,Credit Card,21/11/2021,Emaar Square Mall,300.08,2021-11-21,21,11,2021,2021-11,4,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99372,I134370,C524812,Female,22,Cosmetics,4,162.64,Credit Card,10/11/2022,Kanyon,650.56,2022-11-10,10,11,2022,2022-11,4,45
99385,I484380,C293542,Female,41,Clothing,4,1200.32,Debit Card,23/11/2022,Emaar Square Mall,4801.28,2022-11-23,23,11,2022,2022-11,4,47
99421,I419578,C279804,Male,58,Books,3,45.45,Cash,19/11/2022,Emaar Square Mall,136.35,2022-11-19,19,11,2022,2022-11,4,46
99433,I403904,C142643,Male,28,Toys,1,35.84,Credit Card,2/11/2022,Metrocity,35.84,2022-11-02,2,11,2022,2022-11,4,44
99444,I131678,C119287,Male,24,Toys,1,35.84,Cash,26/11/2021,Mall of Istanbul,35.84,2021-11-26,26,11,2021,2021-11,4,47

In [94]:
data[ data.day == 1].price.sum()

2252638.88

In [96]:
data[ data.year == 2022].price.sum()

31372826.180000003

In [97]:
online_data = pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv")
online_data

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [99]:
def extract_different_times( data , date_column ):
    data["day"] = data[date_column].dt.day
    data["month"] = data[date_column].dt.month
    data["year"] = data[date_column].dt.year
    data["month/year"] = data[date_column].dt.to_period("M")
    data["quarter"] = data[date_column].dt.quarter
    data["week"] = data[date_column].dt.isocalendar().week

In [100]:
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [102]:
data.drop( "customer_id" , axis = 1 )

,invoice_no,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [103]:
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [104]:
data.drop( "customer_id" , axis = 1 , inplace = True )

In [105]:
data

,invoice_no,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [107]:
data.rename( {"payment_method" : "payment method"} , axis = 1 )

,invoice_no,gender,age,category,quantity,price,payment method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [108]:
data

,invoice_no,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [109]:
data.rename( {"payment_method" : "payment method"} , axis = 1, inplace = True  )
data

,invoice_no,gender,age,category,quantity,price,payment method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [110]:
data.payment method

SyntaxError: invalid syntax (916973089.py, line 1)

In [111]:
data.gender

0        Female
1          Male
2          Male
3        Female
4        Female
          ...
99452    Female
99453      Male
99454      Male
99455      Male
99456    Female
Name: gender, Length: 99457, dtype: object

In [112]:
data["payment method"]

0        Credit Card
1         Debit Card
2               Cash
3        Credit Card
4               Cash
            ...
99452    Credit Card
99453           Cash
99454     Debit Card
99455           Cash
99456    Credit Card
Name: payment method, Length: 99457, dtype: object

In [113]:
data.rename({"payment method" : "payment_method"} , axis = 1 , inplace = True )
data

,invoice_no,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [114]:
data.drop_duplicates( inplace = True )

In [115]:
data.duplicated().sum()

0

In [116]:
employees = {
    "name" : ["Ahmed", "Mohamed", "Ali"],
    "salaries" : [1000, 2000, 3000 ]
}

In [117]:
employees_df = pd.DataFrame(employees)
employees_df

      name  salaries
0    Ahmed      1000
1  Mohamed      2000
2      Ali      3000

In [118]:
type(employees_df)

pandas.core.frame.DataFrame

In [ ]:
{ 
    "name" : "Ahmed"
} # map in C++ , json : js ``

In [123]:
new_data = pd.read_csv("customer_shopping_data.csv", header = None )
new_data

/var/folders/_r/3sb29fjj12d916yfxyrhd_gc0000gn/T/ipykernel_10548/2725181962.py:1: DtypeWarning: Columns (3,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  new_data = pd.read_csv("customer_shopping_data.csv", header = None )

,0,1,2,3,4,5,6,7,8,9
0,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
1,I138884,C241288,Female,28,Clothing,5,1500.4,Credit Card,5/8/2022,Kanyon
2,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
3,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
4,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
...,...,...,...,...,...,...,...,...,...,...
99453,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon
99454,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul
99455,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity
99456,I702964,C800631,Male,56,Technology,4,4200.0,Cash,16/03/2021,Istinye Park
99457,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul

In [124]:
new_data = pd.read_csv("customer_shopping_data.csv", header = 1 )
new_data

,I138884,C241288,Female,28,Clothing,5,1500.4,Credit Card,5/8/2022,Kanyon
0,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
1,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
2,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
3,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon
4,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,24/05/2022,Forum Istanbul
...,...,...,...,...,...,...,...,...,...,...
99451,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon
99452,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul
99453,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity
99454,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park
99455,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul

In [125]:
new_data = pd.read_csv("customer_shopping_data.csv", skiprows= 10 )
new_data

,I326945,C283361,Female,60,Clothing,2,600.16,Credit Card,22/08/2021,Kanyon
0,I306368,C240286,Female,36,Food & Beverage,2,10.46,Cash,25/12/2022,Metrocity
1,I139207,C191708,Female,29,Books,1,15.15,Credit Card,28/10/2022,Emaar Square Mall
2,I640508,C225330,Female,67,Toys,4,143.36,Debit Card,31/07/2022,Metrocity
3,I179802,C312861,Male,25,Clothing,2,600.16,Cash,17/11/2022,Cevahir AVM
4,I336189,C555402,Female,67,Clothing,2,600.16,Credit Card,3/6/2022,Kanyon
...,...,...,...,...,...,...,...,...,...,...
99442,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon
99443,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul
99444,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity
99445,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park
99446,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul

In [126]:
new_data = pd.read_csv("customer_shopping_data.csv", nrows = 10  )
new_data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon
5,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,24/05/2022,Forum Istanbul
6,I121056,C151197,Female,49,Cosmetics,1,40.66,Cash,13/03/2022,Istinye Park
7,I293112,C176086,Female,32,Clothing,2,600.16,Credit Card,13/01/2021,Mall of Istanbul
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,4/11/2021,Metrocity
9,I326945,C283361,Female,60,Clothing,2,600.16,Credit Card,22/08/2021,Kanyon

In [127]:
new_data = pd.read_csv("customer_shopping_data.csv", nrows = 1000  )
new_data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon
...,...,...,...,...,...,...,...,...,...,...
995,I248527,C307014,Female,58,Shoes,1,600.17,Credit Card,30/05/2021,Viaport Outlet
996,I103907,C280853,Male,56,Clothing,4,1200.32,Cash,4/10/2022,Forum Istanbul
997,I109766,C106066,Female,57,Food & Beverage,5,26.15,Cash,6/11/2022,Metrocity
998,I195981,C257683,Female,38,Shoes,1,600.17,Credit Card,6/8/2021,Kanyon
999,I583553,C364009,Female,55,Souvenir,3,35.19,Debit Card,24/11/2021,Mall of Istanbul

In [129]:
new_data = pd.read_csv("customer_shopping_data.csv", skiprows = 10 , nrows = 1000  )
new_data

,I326945,C283361,Female,60,Clothing,2,600.16,Credit Card,22/08/2021,Kanyon
0,I306368,C240286,Female,36,Food & Beverage,2,10.46,Cash,25/12/2022,Metrocity
1,I139207,C191708,Female,29,Books,1,15.15,Credit Card,28/10/2022,Emaar Square Mall
2,I640508,C225330,Female,67,Toys,4,143.36,Debit Card,31/07/2022,Metrocity
3,I179802,C312861,Male,25,Clothing,2,600.16,Cash,17/11/2022,Cevahir AVM
4,I336189,C555402,Female,67,Clothing,2,600.16,Credit Card,3/6/2022,Kanyon
...,...,...,...,...,...,...,...,...,...,...
995,I335770,C336888,Male,57,Cosmetics,1,40.66,Debit Card,8/10/2022,Forum Istanbul
996,I273054,C148034,Male,43,Food & Beverage,5,26.15,Debit Card,26/04/2021,Metropol AVM
997,I226742,C724391,Female,56,Clothing,3,900.24,Cash,12/3/2021,Viaport Outlet
998,I259039,C180485,Female,40,Clothing,1,300.08,Debit Card,19/02/2021,Istinye Park
999,I263787,C323464,Female,60,Food & Beverage,4,20.92,Cash,14/10/2021,Metrocity

In [130]:
data

,invoice_no,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41

In [131]:
data.to_csv("WE_Training.csv", index = False)

In [132]:
updated_data = pd.read_csv("WE_Training.csv")
updated_data

,invoice_no,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_amount,date,day,month,year,month/year,quarter,week
0,I138884,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00,2022-08-05,5,8,2022,2022-08,3,31
1,I317333,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53,2021-12-12,12,12,2021,2021-12,4,49
2,I127801,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08,2021-11-09,9,11,2021,2021-11,4,45
3,I173702,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25,2021-05-16,16,5,2021,2021-05,2,19
4,I337046,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40,2021-10-24,24,10,2021,2021-10,4,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99452,I219422,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon,293.25,2022-09-21,21,9,2022,2022-09,3,38
99453,I325143,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul,20.92,2021-09-22,22,9,2021,2021-09,3,38
99454,I824010,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity,20.92,2021-03-28,28,3,2021,2021-03,1,12
99455,I702964,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park,16800.00,2021-03-16,16,3,2021,2021-03,1,11
99456,I232867,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul,105.57,2022-10-15,15,10,2022,2022-10,4,41